// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_qi-uqeKTaC8C0gvzPlbVA5Jv3GL2qq4',
    appId: '1:484586027986:web:fd8f50be6ac9d4067ce60b',
    messagingSenderId: '484586027986',
    projectId: 'tfg-flutter-app',
    authDomain: 'tfg-flutter-app.firebaseapp.com',
    storageBucket: 'tfg-flutter-app.appspot.com',
    measurementId: 'G-7BTFYCZX9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRiM39gcvi5v5oc8iW-AwmCd0ngfxclEQ',
    appId: '1:484586027986:android:1bec261d86685f2e7ce60b',
    messagingSenderId: '484586027986',
    projectId: 'tfg-flutter-app',
    storageBucket: 'tfg-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--ubVBTANLqNsaUkzx02BT12C8m4eM7A',
    appId: '1:484586027986:ios:eca5b9ab178936837ce60b',
    messagingSenderId: '484586027986',
    projectId: 'tfg-flutter-app',
    storageBucket: 'tfg-flutter-app.appspot.com',
    iosClientId:
        '484586027986-def7a0tmfkbtsv8dg3oc9mqoh2q4qrct.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfgFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--ubVBTANLqNsaUkzx02BT12C8m4eM7A',
    appId: '1:484586027986:ios:eca5b9ab178936837ce60b',
    messagingSenderId: '484586027986',
    projectId: 'tfg-flutter-app',
    storageBucket: 'tfg-flutter-app.appspot.com',
    iosClientId:
        '484586027986-def7a0tmfkbtsv8dg3oc9mqoh2q4qrct.apps.googleusercontent.com',
    iosBundleId: 'com.example.tfgFlutterApp',
  );
}
